"""Add password reset fields to User model

Revision ID: 4385cbe8714b
Revises: b8d9a6f21a31
Create Date: 2026-06-01 15:33:31.063004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4385cbe8714b'
down_revision = 'b8d9a6f21a31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER TABLE ADD COLUMN with constraints in batch mode
    # So we add columns without constraints first
    op.add_column('users', sa.Column('reset_token', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('reset_token_expiry', sa.DateTime(), nullable=True))
    
    # Create unique index instead of constraint for SQLite compatibility
    op.create_index('ix_users_reset_token', 'users', ['reset_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_reset_token', table_name='users')
    op.drop_column('users', 'reset_token_expiry')
    op.drop_column('users', 'reset_token')
    # ### end Alembic commands ###
